version: '3.8'
services:
  postgresql:
    image: postgres:15-alpine3.17
    container_name: postgresql
    hostname: postgresql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: javareactdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mister
      TZ: America/Campo_Grande
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s