server:
    port: 8080
    servlet:
        context-path: /

spring:
    jpa:
        database: POSTGRESQL
        hibernate.ddl-auto: update # (create, create-drop, update, none)
        show-sql: true

    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/javareactdb
        username: postgres
        password: mister

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub